import docx
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os

doc_path = r'C:\Users\Kishan Shetty\Downloads\AstraSky-maing\AstraCity_IEEE_Paper_v8.docx'
img_dir = r'C:\Users\Kishan Shetty\Downloads\1RV24IS058'
out_path = r'C:\Users\Kishan Shetty\Downloads\AstraSky-maing\AstraCity_IEEE_Paper_v10_Final.docx'

doc = docx.Document(doc_path)

images_to_insert = [
    {
        "anchor_text": "AstraCity is a spatial decision making support environment",
        "img_file": "Screenshot 2026-06-16 125104.png",
        "caption": "Fig. 1. Core modular architecture of the AstraCity spatial decision-making support environment."
    },
    {
        "anchor_text": "3.1 Geographic Setting",
        "img_file": "Screenshot 2026-06-25 133902.png",
        "caption": "Fig. 2. Volumetric 3D visualization of the 9,471 geo-referenced building footprints within the ward."
    },
    {
        "anchor_text": "4.2 Detection of illegal dumps using DBSCAN cluster",
        "img_file": "Screenshot 2026-06-25 133835.png",
        "caption": "Fig. 3. Predictive spatial heatmap generated by the DBSCAN clustering algorithm."
    },
    {
        "anchor_text": "4. Methodology",
        "img_file": "Screenshot 2026-06-25 133818.png",
        "caption": "Fig. 4. Spatial decomposition of HSR Layout into granular collection zones mapped against the road network."
    },
    {
        "anchor_text": "4.3 Waste Generation Modelling",
        "img_file": "Screenshot 2026-06-16 125236.png",
        "caption": "Fig. 5. Digital Twin Core Engine methodology, showcasing the live translation of waste estimation models."
    },
    {
        "anchor_text": "4.4 Capacitated Vehicle Routing",
        "img_file": "Screenshot 2026-06-16 125223.png",
        "caption": "Fig. 6. The AstraCity Routing Engine interface, visualizing two-tier collection pathways mapping 55 TPD of waste."
    }
]

def insert_image_and_caption_after(paragraph, img_path, caption_text):
    # Create an empty paragraph right after the given one by inserting before the next
    p = paragraph._p
    parent = p.getparent()
    
    # Create new elements to insert
    new_img_p = docx.oxml.shared.OxmlElement('w:p')
    new_cap_p = docx.oxml.shared.OxmlElement('w:p')
    
    # Insert them sequentially into the oxml tree
    idx = list(parent).index(p)
    parent.insert(idx + 1, new_img_p)
    parent.insert(idx + 2, new_cap_p)
    
    # Wrap in Document objects
    img_para = docx.text.paragraph.Paragraph(new_img_p, paragraph._parent)
    cap_para = docx.text.paragraph.Paragraph(new_cap_p, paragraph._parent)
    
    # Add Image
    img_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = img_para.add_run()
    run.add_picture(img_path, width=Inches(3.2)) # IEEE single column width constraint
    
    # Add Caption
    cap_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    cap_run = cap_para.add_run(caption_text)
    cap_run.font.name = 'Times New Roman'
    cap_run.font.size = Pt(9)
    cap_run.italic = True
    
    # Add spacing after caption
    cap_para.paragraph_format.space_after = Pt(12)

# Find anchors and insert
for img_data in images_to_insert:
    anchor = img_data['anchor_text']
    img_path = os.path.join(img_dir, img_data['img_file'])
    
    if not os.path.exists(img_path):
        print(f"Warning: Image not found {img_path}")
        continue
        
    for para in doc.paragraphs:
        if anchor in para.text:
            insert_image_and_caption_after(para, img_path, img_data['caption'])
            print(f"Inserted {img_data['img_file']} after '{anchor}'")
            break

doc.save(out_path)
print(f"Saved generated document to {out_path}")
